-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Mar 24, 2026 at 12:25 AM
-- Server version: 10.4.27-MariaDB
-- PHP Version: 7.4.33

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `rssreader`
--

-- --------------------------------------------------------

--
-- Table structure for table `migrations`
--

CREATE TABLE `migrations` (
  `version` bigint(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `migrations`
--

INSERT INTO `migrations` (`version`) VALUES
(3);

-- --------------------------------------------------------

--
-- Table structure for table `posts`
--

CREATE TABLE `posts` (
  `id` int(11) UNSIGNED NOT NULL,
  `title` varchar(255) NOT NULL,
  `content` text DEFAULT NULL,
  `image_url` varchar(500) DEFAULT NULL,
  `char_count` int(11) DEFAULT NULL,
  `pub_date` datetime DEFAULT NULL,
  `priority` int(11) DEFAULT NULL,
  `feed_url` varchar(500) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `posts`
--

INSERT INTO `posts` (`id`, `title`, `content`, `image_url`, `char_count`, `pub_date`, `priority`, `feed_url`, `created_at`) VALUES
(1, 'Burnt in Ashes, but no clean-up: ECB decides against sacking Stokes &amp; McCullum', '<img border=\"0\" hspace=\"10\" align=\"left\" style=\"margin-top:3px;margin-right:5px;\" src=\"https://timesofindia.indiatimes.com/photo/129758356.cms\" />The review, which was announced soon after the final Test in January, was completed on Monday. ECB chief executive Richard Gould said removing individuals would have been the easier option but the board has chosen not to take that route.', 'https://static.toiimg.com/photo/msid-129758474,imgsize-38320.cms', 383, '2026-03-23 18:25:07', 1, 'https://timesofindia.indiatimes.com/sports/cricket/ashes/burnt-in-the-ashes-but-no-clean-up-ecb-decides-against-sacking-ben-stokes-and-mccullum/articleshow/129758356.cms', '2026-03-23 23:14:28'),
(2, '\'He is like a teacher\': Mayank Yadav reveals Bumrah’s role in injury comeback', '<img border=\"0\" hspace=\"10\" align=\"left\" style=\"margin-top:3px;margin-right:5px;\" src=\"https://timesofindia.indiatimes.com/photo/129758325.cms\" />Fast bowler Mayank Yadav has transformed his fitness and recovery approach after surgery, previously neglecting his body. Now, he prioritizes recovery, nutrition, and sleep, inspired by Jasprit Bumrah\'s guidance. Yadav, who recorded the fastest Indian delivery in IPL 2024, discovered his pace talent early and was inspired by Morne Morkel and Dale Steyn.', 'https://static.toiimg.com/photo/msid-129758400,imgsize-1184089.cms', 501, '2026-03-23 18:23:32', 2, 'https://timesofindia.indiatimes.com/sports/cricket/ipl/top-stories/he-is-like-a-teacher-mayank-yadav-reveals-bumrahs-role-in-injury-comeback/articleshow/129758325.cms', '2026-03-23 23:14:28'),
(3, 'Rahane sends strong message ahead of IPL 2026 with blazing 20-ball fifty', '<img border=\"0\" hspace=\"10\" align=\"left\" style=\"margin-top:3px;margin-right:5px;\" src=\"https://timesofindia.indiatimes.com/photo/129757436.cms\" />Kolkata Knight Riders captain Ajinkya Rahane signaled his intent for IPL 2026 with a rapid 58 off 25 balls in a practice game. Despite a tough 2025, Rahane, the team\'s leading scorer, expressed optimism and a positive outlook towards the upcoming season. He emphasized the importance of a strong start and consistent performance for the revamped KKR squad.', 'https://static.toiimg.com/photo/msid-129757430,imgsize-108782.cms', 502, '2026-03-23 17:27:20', 3, 'https://timesofindia.indiatimes.com/sports/cricket/ipl/top-stories/ajinkya-rahane-sends-strong-message-ahead-of-ipl-2026-with-blazing-20-ball-fifty/articleshow/129757436.cms', '2026-03-23 23:14:29'),
(4, '\'No security concerns\': Bangladesh Cricket Board allows players to join PSL', '<img border=\"0\" hspace=\"10\" align=\"left\" style=\"margin-top:3px;margin-right:5px;\" src=\"https://timesofindia.indiatimes.com/photo/129757303.cms\" />In a statement issued on Monday, the board said it had been in touch with the Ministry of Youth &amp; Sports and the Ministry of Foreign Affairs before taking a decision.', 'https://static.toiimg.com/photo/msid-129757419,imgsize-39454.cms', 316, '2026-03-23 17:17:40', 4, 'https://timesofindia.indiatimes.com/sports/cricket/news/no-security-concerns-bangladesh-cricket-board-allows-players-to-join-psl/articleshow/129757303.cms', '2026-03-23 23:14:29'),
(5, '\'Temple visits not a bad thing\': Axar Patel shares insight into team India culture', '<img border=\"0\" hspace=\"10\" align=\"left\" style=\"margin-top:3px;margin-right:5px;\" src=\"https://timesofindia.indiatimes.com/photo/129756529.cms\" />Indian cricketer Axar Patel revealed the team\'s temple visits during major tournaments are often for convenience and security. He also reiterated his strong disapproval of the Impact Player rule, stating it negatively affects all-rounders like himself by reducing the need for multi-skilled players. Patel\'s views echo those of other senior players.', 'https://static.toiimg.com/photo/msid-129756570,imgsize-144440.cms', 495, '2026-03-23 16:49:32', 5, 'https://timesofindia.indiatimes.com/sports/cricket/ipl/top-stories/temple-visits-not-a-bad-thing-axar-patel-shares-insight-into-team-india-culture/articleshow/129756529.cms', '2026-03-23 23:14:29'),
(6, 'PSL\'s loss, RR\'s gain! Sangakkara hails Shanaka as \'ideal replacement\' for Curran', '<img border=\"0\" hspace=\"10\" align=\"left\" style=\"margin-top:3px;margin-right:5px;\" src=\"https://timesofindia.indiatimes.com/photo/129752419.cms\" />Rajasthan Royals face a setback as Sam Curran is out of IPL 2026 due to injury. Dasun Shanaka has been signed as his replacement. Shanaka brings T20 experience and all-round ability. The Royals begin their campaign against Chennai Super Kings on March 30. They will then play Gujarat Titans, Mumbai Indians, and Royal Challengers Bengaluru.', 'https://static.toiimg.com/photo/msid-129752456,imgsize-1130711.cms', 486, '2026-03-23 13:34:59', 7, 'https://timesofindia.indiatimes.com/sports/cricket/ipl/top-stories/psls-loss-rrs-gain-sangakkara-hails-shanaka-as-ideal-replacement-for-sam-curran/articleshow/129752419.cms', '2026-03-23 23:14:29'),
(7, 'Not Kishan or Abhishek: Irfan Pathan predicts this Indian player to hold SRH together', '<img border=\"0\" hspace=\"10\" align=\"left\" style=\"margin-top:3px;margin-right:5px;\" src=\"https://timesofindia.indiatimes.com/photo/129752027.cms\" />Hyderabad begin their campaign against Royal Challengers Bengaluru (RCB) at the M Chinnaswamy Stadium on March 28. While focus remains on players like Abhishek Sharma, Travis Head, Ishan Kishan, Heinrich Klaasen and Liam Livingstone, Pathan said Reddy could provide balance after a dip in form last season.', 'https://static.toiimg.com/photo/msid-129752487,imgsize-73024.cms', 452, '2026-03-23 13:34:09', 6, 'https://timesofindia.indiatimes.com/sports/cricket/ipl/top-stories/not-kishan-or-abhishek-irfan-pathan-predicts-this-indian-player-to-hold-srh-together/articleshow/129752027.cms', '2026-03-23 23:14:29'),
(8, '\'Don\'t like it\': Axar Patel questions all-rounder\'s role with IPL Impact Player rule', '<img border=\"0\" hspace=\"10\" align=\"left\" style=\"margin-top:3px;margin-right:5px;\" src=\"https://timesofindia.indiatimes.com/photo/129751194.cms\" />Delhi Capitals skipper Axar Patel expressed his dislike for the Impact Player rule ahead of IPL 2026, believing it devalues all-rounders. He feels teams now prioritize specialist players, impacting his role. Despite a challenging bowling season in 2025 due to a finger injury, Axar had a strong batting performance, scoring significantly.', 'https://static.toiimg.com/photo/msid-129751187,imgsize-187540.cms', 484, '2026-03-23 12:55:29', 8, 'https://timesofindia.indiatimes.com/sports/cricket/ipl/top-stories/dont-like-it-axar-patel-questions-all-rounders-role-with-ipl-impact-player-rule/articleshow/129751194.cms', '2026-03-23 23:14:29'),
(9, 'EXCLUSIVE: Less than a week before IPL starts, Bumrah reaches BCCI CoE', '<img border=\"0\" hspace=\"10\" align=\"left\" style=\"margin-top:3px;margin-right:5px;\" src=\"https://timesofindia.indiatimes.com/photo/129751567.cms\" />Jasprit Bumrah has arrived at the BCCI Centre of Excellence in Karnataka, with his presence not confirmed to be injury-related or for routine checks. This comes as Mumbai Indians\' T20 World Cup winning players, including Bumrah, were granted an extended break. MI\'s IPL 2026 campaign begins against KKR on March 29.', 'https://static.toiimg.com/photo/msid-129751540,imgsize-148498.cms', 461, '2026-03-23 12:48:15', 9, 'https://timesofindia.indiatimes.com/sports/cricket/ipl/top-stories/exclusive-less-than-a-week-before-ipl-starts-mumbai-indians-star-jasprit-bumrah-reaches-bcci-coe/articleshow/129751567.cms', '2026-03-23 23:14:29'),
(10, '\'Didn\'t interact much\': Naqvi breaks silence on Kirsten \'interference\' claims', '<img border=\"0\" hspace=\"10\" align=\"left\" style=\"margin-top:3px;margin-right:5px;\" src=\"https://timesofindia.indiatimes.com/photo/129750349.cms\" />Pakistan Cricket Board chief Mohsin Naqvi has responded to former head coach Gary Kirsten\'s claims of significant \"interference\" during his tenure. Naqvi stated he had limited engagement with Kirsten and suggested those directly involved should address the allegations. Kirsten, who resigned after six months, cited constant external noise and punitive actions as major challenges.', 'https://static.toiimg.com/photo/msid-129750358,imgsize-54058.cms', 527, '2026-03-23 12:11:03', 10, 'https://timesofindia.indiatimes.com/sports/cricket/news/didnt-interact-much-mohsin-naqvi-breaks-silence-on-gary-kirsten-interference-claims/articleshow/129750349.cms', '2026-03-23 23:14:29'),
(11, '\'Everyone knows how he became captain\': Ex-India captain\'s cryptic dig at Riyan Parag', '<img border=\"0\" hspace=\"10\" align=\"left\" style=\"margin-top:3px;margin-right:5px;\" src=\"https://timesofindia.indiatimes.com/photo/129749856.cms\" />Former India captain Krishnamachari Srikkanth has raised questions about Riyan Parag\'s appointment as Rajasthan Royals captain for IPL 2026. Srikkanth suggests Parag receives preferential treatment within the franchise. He noted Parag\'s inconsistent performance last season. The Royals\' chances for the upcoming season are seen as unpredictable. Their top order has the potential to win matches.', 'https://static.toiimg.com/photo/msid-129749961,imgsize-91636.cms', 541, '2026-03-23 12:04:27', 11, 'https://timesofindia.indiatimes.com/sports/cricket/ipl/top-stories/everyone-knows-how-he-became-captain-ex-india-captains-cryptic-dig-riyan-parag/articleshow/129749856.cms', '2026-03-23 23:14:29'),
(12, 'Terror threat rocks PSL: Foreign players asked to \'withdraw immediately\'', '<img border=\"0\" hspace=\"10\" align=\"left\" style=\"margin-top:3px;margin-right:5px;\" src=\"https://timesofindia.indiatimes.com/photo/129749033.cms\" />The development comes a day after the league was reduced to a closed-door event at two venues — Karachi and Lahore — amid the ongoing West Asia situation and related security issues.', 'https://static.toiimg.com/photo/msid-129749142,imgsize-32740.cms', 332, '2026-03-23 11:23:58', 12, 'https://timesofindia.indiatimes.com/sports/cricket/news/terror-threat-rocks-pakistans-psl-foreign-players-asked-to-withdraw-immediately/articleshow/129749033.cms', '2026-03-23 23:14:29'),
(13, '\'Surya not being captain is a concern\': Ashwin’s blunt verdict on MI captaincy', '<img border=\"0\" hspace=\"10\" align=\"left\" style=\"margin-top:3px;margin-right:5px;\" src=\"https://timesofindia.indiatimes.com/photo/129749037.cms\" />Ravichandran Ashwin believes Suryakumar Yadav should captain Mumbai Indians, citing his unbeaten T20I record and World Cup triumph. Despite Hardik Pandya\'s past success with Gujarat Titans, Ashwin feels Suryakumar\'s current leadership of India makes him the more logical choice for MI. The franchise faces a leadership dilemma as the IPL 2026 season approaches.', 'https://static.toiimg.com/photo/msid-129749052,imgsize-168756.cms', 507, '2026-03-23 11:23:21', 13, 'https://timesofindia.indiatimes.com/sports/cricket/ipl/top-stories/suryakumar-yadav-not-being-captain-is-a-concern-ashwins-blunt-verdict-on-mi-captaincy/articleshow/129749037.cms', '2026-03-23 23:14:29'),
(14, '\'Vaibhav Sooryavanshi is not professional\': RCB star’s stunning remark goes viral', '<img border=\"0\" hspace=\"10\" align=\"left\" style=\"margin-top:3px;margin-right:5px;\" src=\"https://timesofindia.indiatimes.com/photo/129748323.cms\" />Rajasthan Royals\' young sensation Vaibhav Sooryavanshi, set to turn 15, is poised for IPL 2026 after a record-breaking debut.  His meteoric rise includes international centuries and a match-winning U-19 World Cup performance. While lauded for his talent, questions linger about his professional approach off the field, sparking debate among cricket veterans.', 'https://static.toiimg.com/photo/msid-129748300,imgsize-179800.cms', 504, '2026-03-23 10:46:52', 14, 'https://timesofindia.indiatimes.com/sports/cricket/ipl/top-stories/vaibhav-sooryavanshi-is-not-professional-rcb-stars-stunning-remark-goes-viral/articleshow/129748323.cms', '2026-03-23 23:14:29'),
(15, 'For breaking Virat Kohli\'s record, Pakistan batter named ICC Player of the Month', '<img border=\"0\" hspace=\"10\" align=\"left\" style=\"margin-top:3px;margin-right:5px;\" src=\"https://timesofindia.indiatimes.com/photo/129747789.cms\" />Pakistan\'s Sahibzada Farhan has been crowned ICC Men\'s Player of the Month for February 2026 after smashing Virat Kohli\'s T20 World Cup record with 383 runs. India\'s Arundhati Reddy also earned the Women\'s Player of the Month award for her stellar bowling performance in Australia. Both players expressed immense pride in their achievements.', 'https://static.toiimg.com/photo/msid-129747968,imgsize-71186.cms', 487, '2026-03-23 10:20:11', 15, 'https://timesofindia.indiatimes.com/sports/cricket/news/for-breaking-virat-kohlis-record-pakistan-batter-named-icc-player-of-the-month/articleshow/129747789.cms', '2026-03-23 23:14:29'),
(16, 'IPL 2026: Jitesh smokes 81 off 37; Virat strikes at 241 in RCB warm-up', '<img border=\"0\" hspace=\"10\" align=\"left\" style=\"margin-top:3px;margin-right:5px;\" src=\"https://timesofindia.indiatimes.com/photo/129747606.cms\" />Defending champions Royal Challengers Bengaluru held their first warm-up game for IPL 2026, with Virat Kohli showing good form. Jitesh Sharma starred with a blistering 81, while Rajat Patidar sealed the win for Team Krunal. RCB begin their title defence against Sunrisers Hyderabad on March 28, facing player unavailability.', 'https://static.toiimg.com/photo/msid-129747809,imgsize-35108.cms', 470, '2026-03-23 10:12:39', 16, 'https://timesofindia.indiatimes.com/sports/cricket/ipl/top-stories/ipl-2026-jitesh-sharma-smokes-81-off-37-virat-kohli-strikes-at-241-in-rcb-warm-up/articleshow/129747606.cms', '2026-03-23 23:14:29'),
(17, 'IPL 2026: \'No update\' on Starc, DC\'s Axar says \'no temptation to replace\' the pacer', '<img border=\"0\" hspace=\"10\" align=\"left\" style=\"margin-top:3px;margin-right:5px;\" src=\"https://timesofindia.indiatimes.com/photo/129747264.cms\" />Delhi Capitals are awaiting Cricket Australia\'s clearance for pace spearhead Mitchell Starc\'s participation in IPL 2026. While coach Hemang Badani confirmed no official update, captain Axar Patel and Director of Cricket Venugopal Rao expressed optimism about his eventual arrival. Starc, 36, is expected to miss initial matches due to workload management.', 'https://static.toiimg.com/photo/msid-129747423,imgsize-136688.cms', 501, '2026-03-23 09:46:00', 17, 'https://timesofindia.indiatimes.com/sports/cricket/ipl/top-stories/ipl-2026-no-update-on-starc-dcs-axar-says-no-temptation-to-replace-the-pacer/articleshow/129747264.cms', '2026-03-23 23:14:29'),
(18, '\'Gautam Gambhir does not need to be rude, rough\': Ganguly', '<img border=\"0\" hspace=\"10\" align=\"left\" style=\"margin-top:3px;margin-right:5px;\" src=\"https://timesofindia.indiatimes.com/photo/129747224.cms\" />Sourav Ganguly lauded Gautam Gambhir\'s coaching success, highlighting his T20 World Cup and Champions Trophy wins. While acknowledging Gambhir\'s aggressive style, Ganguly believes he doesn\'t need to be rude, calling him a \"good man\" and a competitor. Ganguly expressed confidence in Gambhir improving his Test coaching, especially on good wickets, and expects him to master away tours.', 'https://static.toiimg.com/photo/msid-129747321,imgsize-58810.cms', 531, '2026-03-23 09:45:23', 18, 'https://timesofindia.indiatimes.com/sports/cricket/news/gautam-gambhir-does-not-need-to-be-rude-rough-because-he-is-a-good-man-sourav-ganguly/articleshow/129747224.cms', '2026-03-23 23:14:29'),
(19, 'IPL 2026 Build-up Live: Fan parks to be hosted across 15 cities; Kohli shines in RCB warm-up', '<img border=\"0\" hspace=\"10\" align=\"left\" style=\"margin-top:3px;margin-right:5px;\" src=\"https://timesofindia.indiatimes.com/photo/129743717.cms\" />', 'https://static.toiimg.com/photo/msid-129743717,imgsize-47986.cms', 146, '2026-03-23 06:25:28', 19, 'https://timesofindia.indiatimes.com/sports/cricket/ipl-2026-live-updates-breaking-news-schedule-team-squads-captains-chennai-super-kings-mumbai-indians-rcb-rr-latest-news/liveblog/129743717.cms', '2026-03-23 23:14:29'),
(20, 'Dhoni to play for CSK till 60! His \'I can try\' reply sends fans into frenzy - WATCH', '<img border=\"0\" hspace=\"10\" align=\"left\" style=\"margin-top:3px;margin-right:5px;\" src=\"https://timesofindia.indiatimes.com/photo/129743533.cms\" />Fans eagerly await MS Dhoni\'s IPL future, with many hoping he continues beyond 2026. When questioned about retirement, the former CSK captain offered a subtle hint, stating, \"It is very difficult. It is on the way down, not on the way up. But I will try,\" sparking thunderous applause from the excited crowd.', 'https://static.toiimg.com/photo/msid-129743598,imgsize-39382.cms', 454, '2026-03-23 06:19:14', 20, 'https://timesofindia.indiatimes.com/sports/cricket/ipl/top-stories/dhoni-to-play-for-csk-till-60-his-i-can-try-reply-sends-fans-into-frenzy-watch/articleshow/129743533.cms', '2026-03-23 23:14:29'),
(21, 'Dinesh Karthik and Dipika Pallikal share photos from their Seemandham; Anushka Sharma congratulates new parents', 'Cricketer Dinesh Karthik and squash star Dipika Pallikal joyfully welcomed their baby girl, Raaha, marking their third child. The couple recently celebrated their Seemandham, sharing heartwarming photos. Meanwhile, actress Anushka Sharma, reportedly living in the UK, is rumored to be making a film comeback in Atlee\'s ambitious project AA22xA6, potentially her Telugu debut.', 'https://static.toiimg.com/photo/47529300.cms', 375, '2026-03-24 00:07:11', 21, 'https://timesofindia.indiatimes.com/entertainment/hindi/bollywood/news/dinesh-karthik-and-dipika-pallikal-share-photos-from-their-seemandham-anushka-sharma-congratulates-new-parents/articleshow/129764556.cms', '2026-03-23 23:14:35'),
(22, '“Fake a** love”: Cardi B slammed online over Stefon Diggs claim that never happened', 'A viral post claiming a dramatic confrontation between Cardi B and Stefon Diggs quickly spread online, sparking heated reactions. However, no credible evidence supports the story, and it appears to be entirely false. The incident highlights how easily misinformation can mislead audiences, turning unverified claims into widely accepted narratives before facts are checked.', 'https://static.toiimg.com/photo/47529300.cms', 373, '2026-03-24 00:03:17', 22, 'https://timesofindia.indiatimes.com/sports/nfl/news/fake-a-love-cardi-b-slammed-online-over-stefon-diggs-claim-that-never-happened/articleshow/129751115.cms', '2026-03-23 23:14:35'),
(23, 'SC: Mamata government hell-bent on impeding Kolkata Metro project', 'The Supreme Court sternly criticized the West Bengal government for obstructing the Kolkata Metro Orange Line\'s completion, calling their appeal \"frivolous\" and an \"obstinate anti-development agenda.\" The court rejected the state\'s plea for time until May, citing elections, and emphasized the government\'s dereliction of duty in delaying a vital public transport project.', 'https://static.toiimg.com/photo/47529300.cms', 372, '2026-03-24 00:03:09', 23, 'https://timesofindia.indiatimes.com/india/sc-mamata-government-hell-bent-on-impeding-kolkata-metro-project/articleshow/129764564.cms', '2026-03-23 23:14:35'),
(24, 'Who is Donna Motsinger? Woman awarded $19 million after jury finds Bill Cosby liable in 1972 sexual assault case', 'Who is Donna Motsinger? Woman awarded $19 million after jury finds Bill Cosby liable in 1972 sexual assault case', 'https://static.toiimg.com/photo/47529300.cms', 112, '2026-03-23 23:56:27', 24, 'https://timesofindia.indiatimes.com/world/us/who-is-donna-motsinger-woman-awarded-19-million-after-jury-finds-bill-cosby-liable-in-1972-sexual-assault-case/articleshow/129762175.cms', '2026-03-23 23:14:35'),
(25, 'Parliament seats may be increased to 816 for 1/3rd women\'s reservation', 'The government plans to introduce bills for one-third women\'s reservation in Lok Sabha and assembly polls, potentially increasing Lok Sabha seats to 816. This move aims to empower women and reshape the political landscape. Implementation hinges on delimitation, with a proposal to use the 2011 census data to ensure the quota is effective by the 2029 elections.', 'https://static.toiimg.com/photo/47529300.cms', 361, '2026-03-23 23:53:11', 25, 'https://timesofindia.indiatimes.com/india/parliament-seats-may-be-increased-to-816-for-1/3rd-womens-reservation/articleshow/129764257.cms', '2026-03-23 23:14:35'),
(26, 'Hidden facts about MLB star Edwin Diaz and Nashaly Mercado’s love story', 'Edwin Diaz and Nashaly Mercado\'s relationship, which began in 2012, has weathered the ups and downs of his baseball career, from minor league struggles to becoming a star closer. Married in 2019, they have three sons and Mercado has provided unwavering support through injuries and career changes, including their recent move to Los Angeles.', 'https://static.toiimg.com/photo/47529300.cms', 341, '2026-03-23 23:39:50', 26, 'https://timesofindia.indiatimes.com/sports/mlb/news/hidden-facts-about-mlb-star-edwin-diaz-and-nashaly-mercados-love-story/articleshow/129762867.cms', '2026-03-23 23:14:35'),
(27, 'What happened between Dayton James Webber and Bradrick Michael Wells inside car before shooting? Witnesses describe tense final moments', 'Dayton James Webber, a professional cornhole player, has been accused of killing Bradrick Michael Wells during an argument inside a car in Maryland. Witnesses shared key details with police. Webber was later found in Virginia and arrested. He now faces serious murder charges as authorities continue investigating the case and gather more information.', 'https://static.toiimg.com/photo/47529300.cms', 351, '2026-03-23 23:39:19', 27, 'https://timesofindia.indiatimes.com/sports/international-sports/what-happened-between-dayton-james-webber-and-bradrick-michael-wells-inside-car-before-shooting-witnesses-describe-tense-final-moments/articleshow/129763574.cms', '2026-03-23 23:14:35'),
(28, 'Wedding leak drama: Travis Kelce goes into damage control mode after Taylor Swift wedding details surface', 'Travis Kelce is reportedly investigating his inner circle after private wedding details with Taylor Swift were leaked. The breach has upset Swift and raised concerns about trust and security. Determined to find the source, Kelce is treating the situation seriously as the couple reassesses privacy measures ahead of their highly anticipated summer wedding.', 'https://static.toiimg.com/photo/47529300.cms', 356, '2026-03-23 23:38:53', 28, 'https://timesofindia.indiatimes.com/sports/nfl/news/wedding-leak-drama-travis-kelce-goes-into-damage-control-mode-after-taylor-swift-wedding-details-surface/articleshow/129750861.cms', '2026-03-23 23:14:35'),
(29, 'Joe Jonas spotted KISSING girlfriend Tatiana Gabriela at Miami airport - WATCH', 'Joe Jonas has publicly displayed his new relationship with Tatiana Gabriela, sharing a passionate reunion at Miami airport. The couple, reportedly dating since summer 2025, were seen engaging in significant public displays of affection, marking a new chapter after his divorce from Sophie Turner. This marks Jonas\'s first high-profile romance since his split.', 'https://static.toiimg.com/photo/47529300.cms', 359, '2026-03-23 23:37:02', 29, 'https://timesofindia.indiatimes.com/entertainment/english/hollywood/news/joe-jonas-spotted-kissing-girlfriend-tatiana-gabriela-years-after-divorce-from-sophie-turner/articleshow/129762678.cms', '2026-03-23 23:14:35'),
(30, 'Piers Morgan shares bold Tottenham relegation comment after Arsenal loss as Premier League FA Cup Champions League hopes continue', 'Piers Morgan reacted to Arsenal’s Carabao Cup final loss with humor, saying their “quintuple dream” is over but a different “quadruple” is still possible. He joked about Tottenham Hotspur getting relegated while praising Arsenal fans’ reactions. Despite the defeat, Mikel Arteta’s team remain in the Premier League, FA Cup, and UEFA Champions League races.', 'https://static.toiimg.com/photo/47529300.cms', 370, '2026-03-23 23:36:25', 30, 'https://timesofindia.indiatimes.com/sports/international-sports/piers-morgan-shares-bold-tottenham-relegation-comment-after-arsenal-loss-as-premier-league-fa-cup-champions-league-hopes-continue/articleshow/129762307.cms', '2026-03-23 23:14:35'),
(31, 'Josh Allen’s future may go beyond football as his connection with Hailee Steinfeld opens new doors ahead of their first child', 'Josh Allen, the Buffalo Bills’ star player, is all set to step into a new chapter in his life alongside his wife, the BAFTA nominated actress, Hailee Steinfeld. As the two gear up to become parents in the next few weeks, it seems Josh Allen might be working on a new career soon and it could be because of Hailee Steinfeld.', 'https://static.toiimg.com/photo/47529300.cms', 325, '2026-03-23 23:35:44', 31, 'https://timesofindia.indiatimes.com/sports/nfl/news/josh-allens-future-may-go-beyond-football-as-his-connection-with-hailee-steinfeld-opens-new-doors-ahead-of-their-first-child/articleshow/129762329.cms', '2026-03-23 23:14:35'),
(32, '“He is a b***h”: Cardi B’s controversial remark sparks chaos as she shuts down Stefon Diggs’ attempts to win her back', 'Stefon Diggs, the popular wide receiver, faces a pretty unstable future in the league as his personal life with Cardi B remains messy after she ended things with him last month. While Stefon Diggs has tried to win her back, Cardi B\'s controversial remark has sparked chaos as fans remain confused whether it was hinted at the star player or Offset.', 'https://static.toiimg.com/photo/47529300.cms', 348, '2026-03-23 23:34:55', 32, 'https://timesofindia.indiatimes.com/sports/nfl/news/he-is-a-bh-cardi-bs-controversial-remark-sparks-chaos-as-she-shuts-down-stefon-diggs-attempts-to-win-her-back/articleshow/129762402.cms', '2026-03-23 23:14:35'),
(33, '“Life would be better without me”: Megan Thee Stallion breaks silence on feeling like a “burden” amid her romance with Klay Thompson', 'Megan Thee Stallion, the six time Grammy winner, has turned heads with her high profile relationship with the Dallas Mavericks’ star player, Klay Thompson. As fans root for an engagement announcement, Megan Thee Stallion\'s heartbreaking statements about feeling \"too much\" have sparked chaos and made fans emotional over the pain she has gone through in her life before she met the NBA legend.', 'https://static.toiimg.com/photo/47529300.cms', 395, '2026-03-23 23:34:28', 33, 'https://timesofindia.indiatimes.com/sports/nba/top-stories/life-would-be-better-without-me-megan-thee-stallion-breaks-silence-on-feeling-like-a-burden-amid-her-romance-with-klay-thompson/articleshow/129760259.cms', '2026-03-23 23:14:35'),
(34, 'Dhanorkar-Andhare open spatdeepens Chandrapur MVA rift', 'Dhanorkar-Andhare open spatdeepens Chandrapur MVA rift', 'https://static.toiimg.com/photo/47529300.cms', 54, '2026-03-23 23:32:04', 34, 'https://timesofindia.indiatimes.com/city/nagpur/dhanorkar-andhare-open-spatdeepens-chandrapur-mva-rift/articleshow/129761203.cms', '2026-03-23 23:14:35'),
(35, 'CoinDCX fraud: Got back 71.6L, have no grievance, court told', 'CoinDCX fraud: Got back 71.6L, have no grievance, court told', 'https://static.toiimg.com/photo/47529300.cms', 60, '2026-03-23 23:31:40', 35, 'https://timesofindia.indiatimes.com/city/mumbai/coindcx-fraud-got-back-71-6l-have-no-grievance-court-told/articleshow/129760958.cms', '2026-03-23 23:14:35'),
(36, '500m-radius of 41 Chennai metro stations to become multimodal hubs', '500m-radius of 41 Chennai metro stations to become multimodal hubs', 'https://static.toiimg.com/photo/47529300.cms', 66, '2026-03-23 23:31:06', 36, 'https://timesofindia.indiatimes.com/city/chennai/500m-radius-of-41-chennai-metro-stations-to-become-multimodal-hubs/articleshow/129761165.cms', '2026-03-23 23:14:35'),
(37, 'Meet Raul Jimenez fiancée Daniela Basso: Inside their love story, their children and family life', 'Raul Jimenez is a top Mexican footballer playing for Fulham with a perfect Premier League penalty record. He recently scored an emotional goal after his father’s death. His fiancée Daniela Basso is a Mexican actress. They met in 2017 and have two children, Arya and Ander. The couple got engaged in February 2025 but have not confirmed a wedding.', 'https://static.toiimg.com/photo/47529300.cms', 349, '2026-03-23 23:29:33', 37, 'https://timesofindia.indiatimes.com/sports/international-sports/meet-raul-jimenez-fiance-daniela-basso-inside-their-love-story-their-children-and-family-life/articleshow/129764253.cms', '2026-03-23 23:14:35'),
(38, 'Conflict posing unprecedented challenges for India, PM Modi tells Parliament', 'Prime Minister Modi highlighted India\'s stance on the West Asia conflict in Parliament. He stressed opposition to attacks on infrastructure and trade routes. India advocates for diplomacy and peaceful resolution. Efforts are underway to ensure safe passage for Indian ships and secure vital supplies like oil and gas. The government is in contact with international partners to maintain maritime safety.', 'https://static.toiimg.com/photo/47529300.cms', 403, '2026-03-23 23:26:07', 38, 'https://timesofindia.indiatimes.com/india/conflict-posing-unprecedented-challenges-for-india-pm-tells-parliament/articleshow/129763699.cms', '2026-03-23 23:14:35'),
(39, 'Dominika Elischerova cause of death: how did the influencer boxing star Mina die at 23?', 'Dominika Elischerova, known as Mina, died at 23 after a truck hit her scooter in Thailand while she was going to training. She suffered serious injuries and could not survive despite medical efforts. Teammate Samir Margina shared details of her condition. Friends and the Clash of the Stars team paid emotional tributes to the young fighter.', 'https://static.toiimg.com/photo/47529300.cms', 341, '2026-03-23 23:25:55', 39, 'https://timesofindia.indiatimes.com/sports/international-sports/dominika-elischerova-cause-of-death-how-did-the-influencer-boxing-star-mina-die-at-23/articleshow/129764140.cms', '2026-03-23 23:14:35'),
(40, 'Fact check: Is Cristiano Ronaldo Jr dating a 27 year old Brazilian model? Viral rumor debunked', 'There is no confirmed proof that Cristiano Ronaldo Jr. is dating a 27 year old Brazilian model. The viral claim comes from social media posts, not trusted news sources. The photos look unclear and possibly unrelated. Major outlets have not reported it. Compared to past rumors, this story lacks basic facts, so it should be treated as unverified and likely false.', 'https://static.toiimg.com/photo/47529300.cms', 363, '2026-03-23 23:22:03', 40, 'https://timesofindia.indiatimes.com/sports/international-sports/fact-check-is-cristiano-ronaldo-jr-dating-a-27-year-old-brazilian-model-viral-rumor-debunked/articleshow/129763871.cms', '2026-03-23 23:14:35'),
(41, 'Who is Jacob Bridgeman’s wife? A closer look at golf star\'s partner and personal life', 'Professional golfer Jacob Bridgeman\'s career success is significantly bolstered by his wife, Haley.  Their college romance at Clemson blossomed into marriage in December 2025. Haley\'s unwavering support, evident at his major 2026 Genesis Invitational victory, highlights their strong partnership and mutual ambition, proving their bond extends far beyond the golf course.', 'https://static.toiimg.com/photo/47529300.cms', 371, '2026-03-23 23:16:20', 41, 'https://timesofindia.indiatimes.com/sports/international-sports/who-is-jacob-bridgemans-wife-a-closer-look-at-golf-stars-partner-and-personal-life/articleshow/129763413.cms', '2026-03-23 23:14:35'),
(42, 'Brandon Nimmo contract details 2026: A look at his salary, bonuses, and contract terms', 'Brandon Nimmo moves to the Texas Rangers in a November 2025 trade.  His eight-year, $162 million contract remains largely intact.  Nimmo will earn $20.25 million in base salary for 2026, plus a $1 million assignment bonus.  The Mets will contribute $5 million to Nimmo\'s salary.  He is set to become a free agent after the 2030 season.', 'https://static.toiimg.com/photo/47529300.cms', 335, '2026-03-23 23:11:41', 42, 'https://timesofindia.indiatimes.com/sports/mlb/news/brandon-nimmo-contract-details-2026-a-look-at-his-salary-bonuses-and-contract-terms/articleshow/129763115.cms', '2026-03-23 23:14:35'),
(43, 'What you eat in your 40s may determine how your brain would function later in life', 'A study published in JAMA Neurology, tracking over 1.5 lakh adults, has found that healthier diets in midlife are associated with better memory and thinking abilities later. Those eating more fruits, vegetables, whole grains and fish were less susceptible to cognitive decline and performed better on cognitive tests. The study also flags diets high in red and processed meat and those linked to inflammation or sugar spikes as being associated with poorer brain outcomes.', 'https://static.toiimg.com/photo/47529300.cms', 472, '2026-03-23 23:02:00', 43, 'https://timesofindia.indiatimes.com/india/what-you-eat-in-your-40s-may-determine-how-your-brain-would-function-later-in-life/articleshow/129762415.cms', '2026-03-23 23:14:35'),
(44, '2 India-flagged tankers clear Hormuz; Iran denies taking ransom', 'Two Indian-flagged LPG tankers, Jag Vasant and Pine Gas, carrying substantial cooking gas, successfully navigated the war-torn Strait of Hormuz. This marks the fourth Indian vessel passage since the conflict\'s onset, with four more Indian ships and crews awaiting safe transit.  The government is prioritizing their secure passage amid regional tensions.', 'https://static.toiimg.com/photo/47529300.cms', 354, '2026-03-23 23:00:47', 44, 'https://timesofindia.indiatimes.com/india/2-india-flagged-tankers-clear-hormuz-iran-denies-taking-ransom/articleshow/129762666.cms', '2026-03-23 23:14:35'),
(45, 'Taylor Swift and Travis Kelce reportedly at odds over a crucial detail in their seemingly perfect relationship ahead of their wedding', 'Taylor Swift and Travis Kelce have seemed close to a picture perfect couple ever since the two went public with their romance in 2023. But it seems as the two near their wedding date, Taylor Swift and Travis Kelce\'s thoughts are clashing as they are worried about different things in their lives. The wedding details have also been made public.', 'https://static.toiimg.com/photo/47529300.cms', 344, '2026-03-23 23:00:21', 45, 'https://timesofindia.indiatimes.com/sports/nfl/news/taylor-swift-and-travis-kelce-reportedly-at-odds-over-a-crucial-detail-in-their-seemingly-perfect-relationship-ahead-of-their-wedding/articleshow/129762403.cms', '2026-03-23 23:14:35'),
(46, 'Your next LPG refill could be of 10kg instead of regular 14.2kg', 'Oil marketing companies are reportedly considering delivering underweight LPG cylinders to ensure more equitable distribution amid critical availability. While the petroleum ministry dismisses these reports as speculative, refiners confirm the proposal is under government consideration. Increased domestic production is now meeting a higher percentage of demand, despite disruptions in West Asia impacting imports.', 'https://static.toiimg.com/photo/47529300.cms', 415, '2026-03-23 22:59:57', 46, 'https://timesofindia.indiatimes.com/india/your-next-lpg-refill-could-be-of-10kg-instead-of-regular-14-2kg/articleshow/129762430.cms', '2026-03-23 23:14:35'),
(47, '\'Moana\' Trailer: Catherine Laga\'aia, Dwayne Johnson set sail with Heihei and Pua in live-action trailer; fans react to The Rock\'s Maui first-look', 'Disney\'s live-action \'Moana\' trailer has arrived, showcasing Catherine Laga\'aia as Moana and Dwayne Johnson as Maui. While fans are excited for the adventure, some are critiquing Johnson\'s portrayal and the film\'s overall aesthetic compared to the animated original. The movie, featuring original songs, hits theaters July 10, 2026.', 'https://static.toiimg.com/photo/47529300.cms', 332, '2026-03-23 22:50:19', 47, 'https://timesofindia.indiatimes.com/entertainment/english/hollywood/news/moana-trailer-catherine-lagaaia-dwayne-johnson-set-sail-with-heihei-and-pua-in-live-action-trailer-fans-react-to-the-rocks-maui-first-look/articleshow/129762355.cms', '2026-03-23 23:14:35'),
(48, 'PM Modi: India has strategic petro reserves of over 53 lakh tonne', 'Prime Minister Narendra Modi assured that the government is actively working to maintain uninterrupted supplies of essential commodities like petrol, diesel, gas, and fertilizers amidst West Asian conflicts. Diversified energy import sources, increased ethanol blending, and extensive railway electrification have significantly reduced dependence on fossil fuels, bolstering India\'s energy security.', 'https://static.toiimg.com/photo/47529300.cms', 399, '2026-03-23 22:46:51', 48, 'https://timesofindia.indiatimes.com/india/pm-modi-india-has-strategic-petro-reserves-of-over-53-lakh-tonne/articleshow/129762605.cms', '2026-03-23 23:14:35'),
(49, 'Rupee slides 35p to close at record low of 93.98 vs dollar', 'Rupee slides 35p to close at record low of 93.98 vs dollar', 'https://static.toiimg.com/photo/47529300.cms', 58, '2026-03-23 22:28:44', 49, 'https://timesofindia.indiatimes.com/business/india-business/rupee-slides-35p-to-close-at-record-low-of-93-98-vs-dollar/articleshow/129762373.cms', '2026-03-23 23:14:35'),
(50, 'Nana Patekar breaks silence on Welcome 4 with Anil Kapoor and Paresh Rawal: \'Agar behtareen hogi, toh zaroor karenge\'', 'Veteran actor Nana Patekar has weighed in on the growing chatter around Welcome 4, even as producer Firoz Nadiadwala recently confirmed that the fourth instalment of the hit comedy franchise is in the scripting stage. While fans are excited about the possible return of iconic characters, Nana has made it clear that he will come on board only if the film lives up to expectations.', 'https://static.toiimg.com/photo/47529300.cms', 381, '2026-03-23 22:17:38', 50, 'https://timesofindia.indiatimes.com/entertainment/hindi/bollywood/news/nana-patekar-breaks-silence-on-welcome-4-with-anil-kapoor-and-paresh-rawal-agar-behtareen-hogi-toh-zaroor-karenge/articleshow/129762363.cms', '2026-03-23 23:14:35'),
(51, 'What happened to boxer Isis Sio after a brutal first round knockout? 19 year old in critical condition after California fight', 'Isis Sio, a 19-year-old boxer, is in a medically induced coma after a first-round knockout loss to Jocelyn Camarillo in California on March 21. She is being treated in intensive care at Loma Linda University Health. The incident has raised serious concerns about fighter safety, recovery time, and decisions around her quick return after a recent knockout loss.', 'https://static.toiimg.com/photo/47529300.cms', 361, '2026-03-23 22:16:14', 51, 'https://timesofindia.indiatimes.com/sports/international-sports/what-happened-to-boxer-isis-sio-after-a-brutal-first-round-knockout-19-year-old-in-critical-condition-after-california-fight/articleshow/129762298.cms', '2026-03-23 23:14:35'),
(52, 'Dak Prescott and Sarah Jane Ramos’ split takes a new turn as he seemingly disappears from his children’s lives', 'Dak Prescott, the Dallas Cowboys’ star player, and his former fiancée, Sarah Jane Ramos, had planned a multi million dollar, lavish Lake Como wedding for next month. While fans are still shocked by the cheating allegations that have hit Dak Prescott, his silence has sparked major concern as he has seemingly disappeared from the public eye and from his daughters\' lives.', 'https://static.toiimg.com/photo/47529300.cms', 374, '2026-03-23 22:15:42', 52, 'https://timesofindia.indiatimes.com/sports/nfl/news/dak-prescott-and-sarah-jane-ramos-split-takes-a-new-turn-as-he-seemingly-disappears-from-his-childrens-lives/articleshow/129762309.cms', '2026-03-23 23:14:35'),
(53, 'What happened to Perez Hilton? YouTuber reveals serious health scare that led to hospital stay and surgery', 'Perez Hilton revealed that a simple flu turned into a serious health crisis after he took medicine without food. He developed an ulcer, perforation, and sepsis, leading to surgery and a 21-day hospital stay. He faced multiple complications but is now recovering. The experience changed his life, making him focus more on health, family, and faith.', 'https://static.toiimg.com/photo/47529300.cms', 347, '2026-03-23 22:15:02', 53, 'https://timesofindia.indiatimes.com/world/us-streamers/what-happened-to-perez-hilton-youtuber-reveals-serious-health-scare-that-led-to-hospital-stay-and-surgery/articleshow/129762321.cms', '2026-03-23 23:14:35'),
(54, 'What happened to Daniel Robert as Phillies pitcher collapses during very scary bullpen moment in spring training', 'Daniel Robert collapsed during a bullpen session with the Philadelphia Phillies after a cardiac event, raising fresh concern about his health. He was taken to hospital and is now stable. The incident is linked to a similar episode in October. Despite the scare, Robert remains thankful to the Phillies and his wife for their strong support.', 'https://static.toiimg.com/photo/47529300.cms', 340, '2026-03-23 22:14:28', 54, 'https://timesofindia.indiatimes.com/sports/mlb/news/what-happened-to-daniel-robert-as-phillies-pitcher-collapses-during-very-scary-bullpen-moment-in-spring-training/articleshow/129762295.cms', '2026-03-23 23:14:35'),
(55, 'Sebi tightens disclosures for top officials', 'Sebi\'s board has greenlit significant disclosure rule changes for its top brass, including public asset declarations for chairmen and whole-time members, aligning with conflict-of-interest committee recommendations. These officials will now be classified as \'insiders\' with investment restrictions similar to employees. The regulator also approved netting benefits for foreign portfolio investors in equity trades.', 'https://static.toiimg.com/photo/47529300.cms', 414, '2026-03-23 22:07:47', 55, 'https://timesofindia.indiatimes.com/business/india-business/sebi-tightens-disclosures-for-top-officials/articleshow/129762353.cms', '2026-03-23 23:14:35'),
(56, 'Independent directors must act responsibly: Sebi chief', 'Sebi Chairman Tuhin Kanta Pandey emphasized that independent directors must act responsibly and avoid vague insinuations, following Atanu Chakraborty\'s resignation from HDFC Bank. Chakraborty cited \"happenings and practices\" not aligning with his values, leading to a significant drop in the bank\'s stock value. Pandey stressed the need for clear documentation of ethical concerns in meeting minutes.', 'https://static.toiimg.com/photo/47529300.cms', 400, '2026-03-23 22:03:32', 56, 'https://timesofindia.indiatimes.com/business/india-business/independent-directors-must-act-responsibly-sebi-chief/articleshow/129762334.cms', '2026-03-23 23:14:35'),
(57, 'Is Cooper Flagg playing tonight vs the Golden State Warriors? Latest update on the Dallas Mavericks star\'s injury report (March 23, 2026)', 'Dallas Mavericks host Golden State Warriors on March 23, 2026. Both teams face player absences due to injuries. Cooper Flagg is expected to start for Dallas and play a significant role. His performance will be key as Dallas aims to break a losing streak against a similarly affected Warriors squad.', 'https://static.toiimg.com/photo/47529300.cms', 298, '2026-03-23 21:58:27', 57, 'https://timesofindia.indiatimes.com/sports/nba/top-stories/is-cooper-flagg-playing-tonight-vs-the-golden-state-warriors-latest-update-on-the-dallas-mavericks-stars-injury-report-march-23-2026/articleshow/129745931.cms', '2026-03-23 23:14:35'),
(58, 'Is Stephen Curry playing tonight vs the Dallas Mavericks? Latest update on the Golden State Warriors star\'s injury report (March 23, 2026)', 'Stephen Curry will miss the Golden State Warriors\' March 23rd game against the Dallas Mavericks due to a lingering right knee injury. The team, already battling other injuries and a road losing streak, needs wins to stay in the play-in race. Curry\'s absence forces a shift in offensive strategy and increases the roles of other players.', 'https://static.toiimg.com/photo/47529300.cms', 336, '2026-03-23 21:57:05', 58, 'https://timesofindia.indiatimes.com/sports/nba/top-stories/is-stephen-curry-playing-tonight-vs-the-dallas-mavericks-latest-update-on-the-golden-state-warriors-stars-injury-report-march-23-2026/articleshow/129745145.cms', '2026-03-23 23:14:35'),
(59, 'Companies Act seeks to allow new exec compensation tools', 'Finance Minister Nirmala Sitharaman has introduced significant amendments to the Companies Act, aiming to decriminalize procedural defaults and boost flexibility in share buybacks. The proposed changes also introduce new executive compensation instruments and streamline merger processes. Special benches for the National Company Law Tribunal are planned, alongside relaxations for small companies regarding CSR requirements.', 'https://static.toiimg.com/photo/47529300.cms', 425, '2026-03-23 21:51:50', 59, 'https://timesofindia.indiatimes.com/business/india-business/companies-act-seeks-to-allow-new-exec-compensation-tools/articleshow/129762320.cms', '2026-03-23 23:14:35'),
(60, 'Golden State Warriors vs Dallas Mavericks injury report: Who\'s playing, injured and questionable players, head-to-head records, team stats, and more (March 23, 2026)', 'Injuries heavily influence the March 23 clash between the Warriors and Mavericks. Golden State, battling for a play-in spot, faces significant absences including Stephen Curry. Dallas, further down the standings, is also short-handed. The game hinges on available players, execution, and pace, with Draymond Green and Jonathan Kuminga expected to step up for the Warriors.', 'https://static.toiimg.com/photo/47529300.cms', 372, '2026-03-23 21:51:10', 60, 'https://timesofindia.indiatimes.com/sports/nba/top-stories/golden-state-warriors-vs-dallas-mavericks-injury-report-whos-playing-injured-and-questionable-players-head-to-head-records-team-stats-and-more-march-23-2026/articleshow/129742541.cms', '2026-03-23 23:14:35'),
(61, 'Is Ja Morant playing tonight vs the Atlanta Hawks? Latest update on the Memphis Grizzlies star\'s injury report (March 23, 2026)', 'Memphis Grizzlies star Ja Morant will miss the March 23rd game against Atlanta due to a lingering left elbow UCL sprain. His return is now uncertain, with no clear timeline for his comeback. The team, already navigating several other injuries and a rebuilding phase, faces a tough road matchup against a favored Hawks squad.', 'https://static.toiimg.com/photo/47529300.cms', 324, '2026-03-23 21:47:35', 61, 'https://timesofindia.indiatimes.com/sports/nba/top-stories/is-ja-morant-playing-tonight-vs-the-atlanta-hawks-latest-update-on-the-memphis-grizzlies-stars-injury-report-march-23-2026/articleshow/129742136.cms', '2026-03-23 23:14:35'),
(62, 'Is Victor Wembanyama playing tonight vs the Miami Heat? Latest update on the San Antonio Spurs star\'s injury report (March 23, 2026)', 'Spurs star Victor Wembanyama is cleared to play against the Miami Heat on March 23, bolstering the San Antonio Spurs\' lineup.  The Spurs, on a five-game winning streak, will rely on Wembanyama\'s dominant presence in the paint to extend their success.  Miami faces potential key absences, potentially impacting their playoff push.', 'https://static.toiimg.com/photo/47529300.cms', 329, '2026-03-23 21:46:47', 62, 'https://timesofindia.indiatimes.com/sports/nba/top-stories/is-victor-wembanyama-playing-tonight-vs-the-miami-heat-latest-update-on-the-san-antonio-spurs-stars-injury-report-march-23-2026/articleshow/129742039.cms', '2026-03-23 23:14:35'),
(63, 'Upside risk to prices as West Asia simmers: RBI', 'India\'s economy shows resilience, but the Reserve Bank of India notes rising price risks. A severe global conflict in West Asia has disrupted oil and commodity markets, causing price surges and volatility. This geopolitical shock is impacting financial systems, leading to equity market sell-offs and pressure on emerging market currencies, including the Indian Rupee.', 'https://static.toiimg.com/photo/47529300.cms', 368, '2026-03-23 21:43:23', 63, 'https://timesofindia.indiatimes.com/business/india-business/upside-risk-to-prices-as-west-asia-simmers-rbi/articleshow/129762301.cms', '2026-03-23 23:14:35'),
(64, 'RBI turns net buyer of dollars in Jan', 'RBI turns net buyer of dollars in Jan', 'https://static.toiimg.com/photo/47529300.cms', 37, '2026-03-23 21:37:46', 64, 'https://timesofindia.indiatimes.com/business/india-business/rbi-turns-net-buyer-of-dollars-in-jan/articleshow/129762279.cms', '2026-03-23 23:14:35'),
(65, 'Gemini Horoscope Today, March 24, 2026: Say no to shopping, and pause before replying to family messages', 'In these challenging times, it’s crucial to be fiscally responsible as expenses can often surpass earnings. Relationships with family require thoughtful consideration to maintain harmony. When it comes to partnerships, keep emotions in check and choose peace over conflicts. In your career, channel your energy into essential projects and dodge the unnecessary drama.', 'https://static.toiimg.com/photo/47529300.cms', 369, '2026-03-23 19:51:58', 65, 'https://timesofindia.indiatimes.com/astrology/horoscope/gemini-horoscope-today-march-24-2026-say-no-to-shopping-and-pause-before-replying-to-family-messages/articleshow/129755706.cms', '2026-03-23 23:14:35');
INSERT INTO `posts` (`id`, `title`, `content`, `image_url`, `char_count`, `pub_date`, `priority`, `feed_url`, `created_at`) VALUES
(66, 'Virgo Horoscope Today, March 24, 2026: Your relationship with your spouse may deteriorate if you turn critical', 'Get ready for an exciting day as fortune smiles upon your finances and career, with Jupiter amplifying your ambitions. As your children bring you joy, tread lightly with your words to keep the peace at home. Stay committed to consistent growth in your profession, while students should dedicate time to their studies and review.', 'https://static.toiimg.com/photo/47529300.cms', 328, '2026-03-23 19:51:26', 66, 'https://timesofindia.indiatimes.com/astrology/horoscope/virgo-horoscope-today-march-24-2026-your-relationship-with-your-spouse-may-deteriorate-if-you-turn-critical/articleshow/129755877.cms', '2026-03-23 23:14:35'),
(67, 'Leo Horoscope Today, March 24, 2026: If you’re single, your charm is high', 'Bright days are coming with solar energy igniting optimism and favorable connections starting to surface. As your father\'s health takes a positive turn, it’s important to keep an eye on your mother\'s needs as well. For those seeking love, a spark of romance is imminent. Focus and determination will propel your career and studies forward.', 'https://static.toiimg.com/photo/47529300.cms', 341, '2026-03-23 19:51:12', 67, 'https://timesofindia.indiatimes.com/astrology/horoscope/leo-horoscope-today-march-24-2026-if-youre-single-your-charm-is-high/articleshow/129755874.cms', '2026-03-23 23:14:35'),
(68, 'Libra Horoscope Today, March 24, 2026: If you drive, wear your helmet or seatbelt without fail', 'Stay vigilant on the roads and throughout your day; distractions may catch you off guard. Foster peace in your relationships by steering clear of conflicts that serve no purpose. At the workplace, take your time to ensure everything is accurate and double-checked. Hold off on making any significant financial decisions or spur-of-the-moment buys.', 'https://static.toiimg.com/photo/47529300.cms', 347, '2026-03-23 19:50:58', 68, 'https://timesofindia.indiatimes.com/astrology/horoscope/libra-horoscope-today-march-24-2026-if-you-drive-wear-your-helmet-or-seatbelt-without-fail/articleshow/129756516.cms', '2026-03-23 23:14:35'),
(69, 'Scorpio Horoscope Today, March 24, 2026: Romance flows, but not in a filmi way', 'Today, collaborations sparkle, transforming shared responsibilities and intimate experiences into an easy flow. Remember to choose your words wisely, particularly when communicating with women. Romance can flourish with thoughtful actions. Whether in academics or the corporate world, success stems from teamwork and a strategic approach to seizing opportunities. Focus on building savings rather than indulging in risky ventures.', 'https://static.toiimg.com/photo/47529300.cms', 430, '2026-03-23 19:50:45', 69, 'https://timesofindia.indiatimes.com/astrology/horoscope/scorpio-horoscope-today-march-24-2026-romance-flows-but-not-in-a-filmi-way/articleshow/129756518.cms', '2026-03-23 23:14:35'),
(70, 'Scientists finally uncover what’s hidden beneath the world’s oldest tree, and it’s alive', 'Scientists finally uncover what’s hidden beneath the world’s oldest tree, and it’s alive', 'https://static.toiimg.com/photo/47529300.cms', 94, '2026-03-23 13:29:18', 70, 'https://timesofindia.indiatimes.com/science/scientists-finally-uncover-whats-hidden-beneath-the-worlds-oldest-tree-and-its-alive/articleshow/129752445.cms', '2026-03-23 23:14:35');

-- --------------------------------------------------------

--
-- Table structure for table `post_platforms`
--

CREATE TABLE `post_platforms` (
  `id` int(11) NOT NULL,
  `post_id` int(11) NOT NULL,
  `platform_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `post_platforms`
--

INSERT INTO `post_platforms` (`id`, `post_id`, `platform_id`) VALUES
(1, 1, 2),
(2, 1, 3),
(3, 8, 3);

-- --------------------------------------------------------

--
-- Table structure for table `social_platforms`
--

CREATE TABLE `social_platforms` (
  `id` int(11) NOT NULL,
  `name` varchar(100) NOT NULL,
  `slug` varchar(100) NOT NULL,
  `icon` varchar(100) DEFAULT NULL,
  `color` varchar(20) DEFAULT NULL,
  `max_chars` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `social_platforms`
--

INSERT INTO `social_platforms` (`id`, `name`, `slug`, `icon`, `color`, `max_chars`) VALUES
(1, 'Facebook', 'facebook', 'fab fa-facebook', '#1877F2', 63206),
(2, 'Twitter (X)', 'twitter', 'fab fa-twitter', '#000000', 280),
(3, 'Instagram', 'instagram', 'fab fa-instagram', '#E1306C', 2200),
(4, 'LinkedIn', 'linkedin', 'fab fa-linkedin', '#0077B5', 3000);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `posts`
--
ALTER TABLE `posts`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `post_platforms`
--
ALTER TABLE `post_platforms`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `unique_post_platform` (`post_id`,`platform_id`);

--
-- Indexes for table `social_platforms`
--
ALTER TABLE `social_platforms`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `slug` (`slug`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `posts`
--
ALTER TABLE `posts`
  MODIFY `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=71;

--
-- AUTO_INCREMENT for table `post_platforms`
--
ALTER TABLE `post_platforms`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;

--
-- AUTO_INCREMENT for table `social_platforms`
--
ALTER TABLE `social_platforms`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
